# Generated by Django 3.2.5 on 2021-10-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_links_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='info',
            new_name='detail',
        ),
    ]
