# Generated by Django 4.0 on 2022-01-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_rename_info_links_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='short_url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
